'use strict';
//Below configurations will be issued to customer offline as part of on-boarding process.
module.exports = {
    EQUINIX_INCOMING_QUEUE : '<INCOMING_QUEUE>',
    EQUINIX_INCOMING_QUEUE_CONNECTION_STRING : '<INCOMING_QUEUE_CONNECTION_STRING>',
    EQUINIX_OUTGOING_QUEUE : '<OUTGOING_QUEUE>',
    EQUINIX_OUTGOING_QUEUE_CONNECTION_STRING :'<OUTGOING_QUEUE_CONNECTIOON_STRING>',
    SOURCE_ID : '<SAMPLE_UUID>',
    BLOB_CONNECTION_STRING : '<BLOB_CONNECTION_STRING>',
    AZURE_UPLOAD_BLOB_DIRECTORY : "<AZURE_UPLOAD_BLOB_DIRECTORY>",
    AZURE_UPLOAD_URL : '<AZURE_UPLOAD_URL>',
    AZURE_DOWNLOAD_SASS_TOKEN : '<AZURE_DOWNLOAD_SASS_TOKEN>',
}